apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: postgres
spec:
  version: "11.11"
  storageType: Durable
  storage:
    #    storageClassName: "default"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  # terminationPolicy: DoNotTerminate
